language: node_js
node_js:
  - 18
cache:
  bundler: true
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm run build
  - npm test
after_success:
  - bash .travis.deploy.sh
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: $NPM_USER
  api_key: $NPM_TOKEN
  skip_cleanup: true
